version: "3.9"
services:
  database_clinica:
    image: postgres
    container_name: database_clinica
    restart: always
    ports:
      - 5432:5432
      - 9229:9229
    environment:
      - POSTGRES_USER=esqueci
      - POSTGRES_PASSWORD=esqueci
      - POSTGRES_DB=clinica
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: clinica
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    links:
      - database_clinica
    depends_on:
      - database_clinica

volumes:
  pgdata:
    driver: local
